#include "UwbSensorPlugin.hh"
#include "EcmGeometry.hh"
#include "gtec_uwb/Resolver.hh"

#include <gz/plugin/Register.hh>
#include <gz/sim/Model.hh>
#include <gz/sim/Util.hh>
#include <gz/sim/components/Name.hh>
#include <gz/math/Quaternion.hh>
#include <gz/common/Console.hh>
#include "ranging.pb.h"  // px4::msgs::Ranging (generated by px4_gz_msgs)

namespace gtec_uwb {

void UwbSensorPlugin::Configure(const gz::sim::Entity &entity,
                                const std::shared_ptr<const sdf::Element> &sdf,
                                gz::sim::EntityComponentManager &ecm,
                                gz::sim::EventManager &) {
  this->modelEntity_ = entity;
  gz::sim::Model model(entity);

  double rate = sdf->Get<double>("update_rate", 25.0).first;
  if (rate > 0.0) {
    updatePeriod_ = std::chrono::duration_cast<std::chrono::steady_clock::duration>(
        std::chrono::duration<double>(1.0 / rate));
  }

  params_.allBeaconsAreLOS = sdf->Get<bool>("all_los", false).first;
  params_.returnsAngle     = sdf->Get<bool>("return_angle", false).first;
  params_.tagId            = sdf->Get<int>("tag_id", 0).first;
  params_.tagZOffset       = sdf->Get<double>("tag_z_offset", 0.0).first;
  params_.nlosSoftWallWidth= sdf->Get<double>("nlosSoftWallWidth", 0.25).first;
  anchorPrefix_            = sdf->Get<std::string>("anchor_prefix", "uwb_anchor").first;

  if (sdf->HasElement("tag_link")) {
    std::string ln = sdf->Get<std::string>("tag_link");
    tagLink_ = model.LinkByName(ecm, ln);
    if (tagLink_ == gz::sim::kNullEntity) useParentAsReference_ = true;
  } else {
    useParentAsReference_ = true;
  }

  pub_ = node_.Advertise<px4::msgs::Ranging>("/gtec/toa/ranging");
  gzmsg << "[GTEC UWB] plugin loaded, tag " << params_.tagId << std::endl;
}

void UwbSensorPlugin::PostUpdate(const gz::sim::UpdateInfo &info,
                                 const gz::sim::EntityComponentManager &ecm) {
  if (info.paused) return;
  if (info.simTime - lastUpdate_ < updatePeriod_) return;
  lastUpdate_ = info.simTime;

  // --- tag pose (UwbPlugin.cpp:763-785) ---
  gz::math::Pose3d tagPose = useParentAsReference_
      ? gz::sim::worldPose(modelEntity_, ecm)
      : gz::sim::worldPose(tagLink_, ecm);
  tagPose.Set(gz::math::Vector3d(tagPose.Pos().X(), tagPose.Pos().Y(),
                                 tagPose.Pos().Z() + params_.tagZOffset),
              tagPose.Rot());
  double currentYaw = tagPose.Rot().Yaw();

  auto angles = BuildAngleSweep(currentYaw);

  // --- refresh obstacles + ray-cast callback ---
  BuildObstacleSet(ecm, modelEntity_, obstacles_);
  RayCastFn rayCast = [this](const gz::math::Vector3d &o, const gz::math::Vector3d &t) {
    return obstacles_.Intersect(o, t);
  };

  // --- per anchor ---
  for (const auto &a : FindAnchors(ecm, anchorPrefix_)) {
    gz::math::Pose3d anchorPose = gz::sim::worldPose(a.entity, ecm);
    Measurement meas = ResolveAnchor(tagPose, anchorPose, angles, rayCast,
                                     params_, model_, rng_);
    if (!meas.valid) continue;

    px4::msgs::Ranging msg;
    msg.set_time_usec(
        std::chrono::duration_cast<std::chrono::microseconds>(info.simTime).count());
    msg.set_anchor_id(a.id);
    msg.set_tag_id(params_.tagId);
    msg.set_range(meas.range);
    msg.set_seq(sequence_);
    msg.set_rss(meas.rss);
    msg.set_error_estimation(0.00393973);  // UwbPlugin.cpp:1109
    msg.set_angle(meas.angle);
    pub_.Publish(msg);
  }
  ++sequence_;
}

}  // namespace gtec_uwb

GZ_ADD_PLUGIN(gtec_uwb::UwbSensorPlugin, gz::sim::System,
              gtec_uwb::UwbSensorPlugin::ISystemConfigure,
              gtec_uwb::UwbSensorPlugin::ISystemPostUpdate)
GZ_ADD_PLUGIN_ALIAS(gtec_uwb::UwbSensorPlugin, "gtec::UwbSensorPlugin")
